# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# azure-pipelines-security.yml

trigger:
  - develop
  - staging
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'

steps:
- checkout: self

# Run Microsoft Security DevOps
#- task: MicrosoftSecurityDevOps@1
 # displayName: 'Run Microsoft Security DevOps Analysis'

# Run OWASP Dependency-Check
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- task: Bash@3
  displayName: 'Run OWASP Dependency-Check'
  inputs:
    targetType: 'inline'
    script: |
      wget https://github.com/jeremylong/DependencyCheck/releases/download/v9.0.7/dependency-check-9.0.7-release.zip
      unzip dependency-check-9.0.7-release.zip -d dependency-check
      mkdir odc-data
      ./dependency-check/dependency-check/bin/dependency-check.sh \
        --project "ASP.NET App" \
        --scan . \
        --out odc-report \
        --format HTML \
        --data odc-data \
        --nvdApiKey "$NVD_API_KEY" \
        --enableExperimental
  env:
    NVD_API_KEY: $(NVD_API_KEY)


# Publish Dependency-Check report
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'odc-report'
    artifactName: 'owasp-dependency-check-report'

